layout_spectrum: 0.24280453519895673
typography_spectrum: 0.6641863659024239
color:
  brandStrength: 0.31459965580143034
  lightness: 0.24862592085264623
  saturation: 0.5510079087689519
  rhythmicContrast: 0.5059583650436252
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
name: 1953 Buick Roadmaster 76R
navigation:
  - id: 'http://www.hometownbuick.com/buick-models/1953-buick-models/'
    url: 'http://www.hometownbuick.com/buick-models/1953-buick-models/'
    name: hometownbuick.com
    type: external
